{
 "title": "Geth",
 "description": "Monitor your Ethereum Geth server with Prometheus and Grafana.",
 "tags": [
  "L1",
  "geth",
  "application"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  { "title": "Quick", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Current Block",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "geth_block" }
   ]
  },
  {
   "title": "Gas Price",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "geth_gas_price / 1000000000" }
   ]
  },
  {
   "title": "Since Last Block",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "geth_seconds_last_block" }
   ]
  },
  {
   "title": "Response Time",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "geth_load_time" }
   ]
  },
  {
   "title": "ETH Transfers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "geth_eth_transfers" }
   ]
  },
  {
   "title": "Token Transfers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 17, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "geth_token_transfers" }
   ]
  },
  {
   "title": "Pending Transactions",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "geth_pending_transactions" }
   ]
  },
  {
   "title": "ETH Value",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "geth_block_value" }
   ]
  },
  {
   "title": "Today's Sent ETH",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 4, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    { "expr": "sum(geth_block_value)" }
   ]
  },
  { "title": "Gas", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Gas Price (gwei)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    { "expr": "geth_gas_price / 1000000000", "legendFormat": "Transactions" }
   ]
  },
  {
   "title": "Gas Used",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "geth_block_gas_used", "legendFormat": "Token Transfers" }
   ]
  },
  {
   "title": "Transactions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "Transactions",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      { "expr": "geth_block_transactions", "legendFormat": "Transactions" }
     ]
    },
    {
     "title": "Pending Transactions",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      { "expr": "geth_pending_transactions", "legendFormat": "transactions" }
     ]
    },
    {
     "title": "Contracts Created",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      { "expr": "geth_contracts_created", "legendFormat": "Contracts" }
     ]
    },
    {
     "title": "Ether Transfers",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      { "expr": "geth_eth_transfers", "legendFormat": "ETH" },
      { "expr": "geth_token_transfers", "legendFormat": "Tokens" }
     ]
    }
   ]
  },
  { "title": "Blocks", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Block Difficulty",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "geth_block_difficulty / 10000000000000",
     "legendFormat": "Difficulty"
    }
   ]
  },
  {
   "title": "Block Size",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "geth_block_size_bytes", "legendFormat": "Token Transfers" }
   ]
  },
  {
   "title": "Block Nonce",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "geth_block_nonce / 1000000000000000000",
     "legendFormat": "Nonce"
    }
   ]
  }
 ]
}