{
 "title": "OP Batcher",
 "tags": [
  "L2",
  "op-batcher",
  "batcher",
  "application"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(op_batcher_default_balance,instance)"
    }
   },
   {
    "name": "job",
    "query": {
     "query": "label_values(op_batcher_default_balance{instance=\"$instance\"},job)"
    }
   },
   {
    "name": "le",
    "query": "0.005, 0.01, 0.025, 0.05, 0.1, 0.25, 0.5, 1, 2.5, 5, 10, +Inf"
   }
  ]
 },
 "panels": [
  {
   "title": "Quick",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Default Balance (ETH)",
     "type": "stat",
     "gridPos": { "h": 4, "w": 5, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "op_batcher_default_balance{instance=~\"$instance\", job=~\"$job\"}",
       "legendFormat": "L1 block number"
      },
      {
       "expr": "op_node_default_refs_number{instance=~\"$instance\", job=~\"$job\",layer=\"l2\",type=\"l2_finalized\"}",
       "legendFormat": "L2 block number"
      }
     ]
    },
    {
     "title": "Total TX Submitted",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 5, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "op_batcher_default_batcher_tx_total{instance=~\"$instance\", job=~\"$job\"}",
       "legendFormat": "L1 block number"
      }
     ]
    },
    {
     "title": "Input Bytes Total",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 9, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "op_batcher_default_input_bytes_total{instance=~\"$instance\", job=~\"$job\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Output Bytes Total",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 13, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "op_batcher_default_output_bytes_total{instance=~\"$instance\", job=~\"$job\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Compression Ratio",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 17, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "op_batcher_default_channel_compr_ratio_sum{instance=~\"$instance\", job=~\"$job\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Blocks Added",
     "type": "stat",
     "gridPos": { "h": 4, "w": 5, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "op_batcher_default_blocks_added_count{instance=~\"$instance\", job=~\"$job\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Blob Bytes Used",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 5, "y": 5 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "rate(op_batcher_default_blob_used_bytes_count{instance=~\"$instance\", job=~\"$job\"}[$__rate_interval])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Last Batcher Tx event (epoch)",
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 9, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "op_batcher_default_last_batcher_tx_unix{instance=~\"$instance\", job=~\"$job\"}",
       "legendFormat": "{{stage}}"
      }
     ]
    },
    {
     "title": "Pending Blocks Bytes Total",
     "type": "stat",
     "description": "Total size of transactions in pending blocks as they are fetched from L2",
     "gridPos": { "h": 4, "w": 6, "x": 15, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "op_batcher_default_pending_blocks_bytes_total{instance=~\"$instance\", job=~\"$job\"}",
       "legendFormat": "{{stage}}"
      }
     ]
    },
    {
     "title": "Pending Blocks Count",
     "type": "stat",
     "description": "Number of pending blocks, not added to a channel yet.",
     "gridPos": { "h": 4, "w": 12, "x": 0, "y": 9 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "op_batcher_default_pending_blocks_count{instance=~\"$instance\", job=~\"$job\"}",
       "legendFormat": "{{stage}}"
      }
     ]
    },
    {
     "title": "Ready bytes",
     "type": "stat",
     "description": "Number of bytes ready in the compression buffer.",
     "gridPos": { "h": 4, "w": 5, "x": 12, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "op_batcher_default_ready_bytes{instance=~\"$instance\", job=~\"$job\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Info",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 17, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "op_batcher_default_info{instance=~\"$instance\", job=~\"$job\"}",
       "legendFormat": "{{version}}"
      }
     ]
    },
    {
     "title": "Last Channel event (unix timestamp)",
     "type": "stat",
     "gridPos": { "h": 5, "w": 13, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "epoch" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "op_batcher_default_last_channel_unix{instance=~\"$instance\", job=~\"$job\"}",
       "legendFormat": "{{stage}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Basic",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Input Bytes",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "op_batcher_default_input_bytes{instance=~\"$instance\", job=~\"$job\"}",
       "legendFormat": "{{stage}}"
      }
     ]
    },
    {
     "title": "Channel Total",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 23, "x": 0, "y": 27 },
     "targets": [
      {
       "expr": "op_batcher_default_channel_total{instance=~\"$instance\", job=~\"$job\"}",
       "legendFormat": "{{stage}}"
      }
     ]
    },
    {
     "title": "Reference Latency",
     "type": "timeseries",
     "description": "Different L1/L2 reference block timestamps minus current time, in seconds",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
     "targets": [
      {
       "expr": "op_batcher_default_refs_latency{instance=~\"$instance\", job=~\"$job\"}",
       "legendFormat": "{{layer}} {{type}}"
      }
     ]
    },
    {
     "title": "Reference Number",
     "type": "timeseries",
     "description": "Representing the different L1/L2 reference block numbers",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
     "targets": [
      {
       "expr": "op_batcher_default_refs_number{instance=~\"$instance\", job=~\"$job\"}",
       "legendFormat": "{{layer}} {{type}}"
      }
     ]
    }
   ]
  }
 ]
}