{
 "title": "OP Geth",
 "tags": [
  "L2",
  "op-geth",
  "application",
  "sequencer"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "job",
    "query": {
     "query": "label_values(chain_info{instance=\"$instance\"},job)"
    }
   },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(chain_info,instance)"
    }
   },
   {
    "name": "quantile",
    "query": "0.5, 0.75, 0.95, 0.99, 0.999, 0.9999"
   }
  ]
 },
 "panels": [
  { "title": "Quick", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Current Block",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "chain_head_block{instance=~\"$instance\", job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Executable txs",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "txpool_pending{instance=~\"$instance\", job=~\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Geth Memory Usage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_memory_used{job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Geth CPU Threads",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_cpu_threads{job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Peer Count",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 13, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "p2p_peers{job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Last Received Block",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "chain_head_receipt{instance=~\"$instance\", job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Executable txs",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 4, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "txpool_pending{instance=~\"$instance\", job=~\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total System Memory",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 7, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_memory_used{job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Latest receipt",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "chain_head_receipt{instance=~\"$instance\", job=~\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Local transactions",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 4, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "txpool_local{instance=~\"$instance\", job=~\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Geth Processor Loading",
   "type": "timeseries",
   "gridPos": { "h": 3, "w": 3, "x": 7, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "system_cpu_procload{job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Basic",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Disk Read Activity (bytes/s)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "rate(system_disk_readbytes{job=\"$job\"}[1m])"
      }
     ]
    },
    {
     "title": "Disk Write Activity (bytes/s)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "rate(system_disk_writebytes{job=\"$job\"}[1m])"
      }
     ]
    },
    {
     "title": "Chain Data Disk Size",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "eth_db_chaindata_disk_size{job=\"$job\"}"
      }
     ]
    }
   ]
  },
  { "title": "RPC", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "RPC Requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "rpc_requests{job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Duration all",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "expr": "rpc_duration_all{instance=~\"$instance\", job=~\"$job\", quantile=~\"$quantile\"}",
     "legendFormat": "all"
    }
   ]
  },
  {
   "title": "Duration eth methods",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "rpc_duration_eth_blockNumber_success{instance=~\"$instance\", job=~\"$job\", quantile=~\"$quantile\"}",
     "legendFormat": "eth_blockNumber_success"
    },
    {
     "expr": "rpc_duration_eth_call_failure{instance=~\"$instance\", job=~\"$job\", quantile=~\"$quantile\"}",
     "legendFormat": "eth_call_failure"
    },
    {
     "expr": "rpc_duration_eth_call_success{instance=~\"$instance\", job=~\"$job\", quantile=~\"$quantile\"}",
     "legendFormat": "eth_call_success"
    },
    {
     "expr": "rpc_duration_eth_chainId_success{instance=~\"$instance\", job=~\"$job\", quantile=~\"$quantile\"}",
     "legendFormat": "eth_chainId_success"
    },
    {
     "expr": "rpc_duration_eth_feeHistory_success{instance=~\"$instance\", job=~\"$job\", quantile=~\"$quantile\"}",
     "legendFormat": "eth_feeHistory_success"
    },
    {
     "expr": "rpc_duration_eth_gasPrice_success{instance=~\"$instance\", job=~\"$job\", quantile=~\"$quantile\"}",
     "legendFormat": "eth_gasPrice_success"
    },
    {
     "expr": "rpc_duration_eth_getBalance_success{instance=~\"$instance\", job=~\"$job\", quantile=~\"$quantile\"}",
     "legendFormat": "eth_getBalance_success"
    },
    {
     "expr": "rpc_duration_eth_getBlockByHash_success{instance=~\"$instance\", job=~\"$job\", quantile=~\"$quantile\"}",
     "legendFormat": "eth_getBlockByHash_success"
    },
    {
     "expr": "rpc_duration_eth_getBlockByNumber_success{instance=~\"$instance\", job=~\"$job\", quantile=~\"$quantile\"}",
     "legendFormat": "eth_getBlockByNumber_success"
    },
    {
     "expr": "rpc_duration_eth_getCode_success{instance=~\"$instance\", job=~\"$job\", quantile=~\"$quantile\"}",
     "legendFormat": "eth_getCode_success"
    },
    {
     "expr": "rpc_duration_eth_getProof_success{instance=~\"$instance\", job=~\"$job\", quantile=~\"$quantile\"}",
     "legendFormat": "eth_getProof_success"
    },
    {
     "expr": "rpc_duration_eth_getStorageAt_success{instance=~\"$instance\", job=~\"$job\", quantile=~\"$quantile\"}",
     "legendFormat": "eth_getStorageAt_success"
    },
    {
     "expr": "rpc_duration_eth_getTransactionCount_success{instance=~\"$instance\", job=~\"$job\", quantile=~\"$quantile\"}",
     "legendFormat": "eth_getTransactionCount_success"
    },
    {
     "expr": "rpc_duration_eth_getTransactionReceipt_success{instance=~\"$instance\", job=~\"$job\", quantile=~\"$quantile\"}",
     "legendFormat": "eth_getTransactionReceipt_success"
    }
   ]
  },
  {
   "title": "Duration engine methods",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 21 },
   "targets": [
    {
     "expr": "rpc_duration_engine_forkchoiceUpdatedV1_success{instance=~\"$instance\", job=~\"$job\", quantile=~\"$quantile\"}",
     "legendFormat": "engine_forkchoiceUpdatedV1_success"
    },
    {
     "expr": "rpc_duration_engine_forkchoiceUpdatedV2_failure{instance=~\"$instance\", job=~\"$job\", quantile=~\"$quantile\"}",
     "legendFormat": "engine_forkchoiceUpdatedV2_failure"
    },
    {
     "expr": "rpc_duration_engine_forkchoiceUpdatedV3_success{instance=~\"$instance\", job=~\"$job\", quantile=~\"$quantile\"}",
     "legendFormat": "engine_forkchoiceUpdatedV3_success"
    },
    {
     "expr": "rpc_duration_engine_getPayloadV2_success{instance=~\"$instance\", job=~\"$job\", quantile=~\"$quantile\"}",
     "legendFormat": "engine_getPayloadV2_success"
    },
    {
     "expr": "rpc_duration_engine_newPayloadV2_success{instance=~\"$instance\", job=~\"$job\", quantile=~\"$quantile\"}",
     "legendFormat": "engine_newPayloadV2_success"
    }
   ]
  },
  {
   "title": "Duration net methods",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "rpc_duration_net_version_success{instance=~\"$instance\", job=~\"$job\", quantile=~\"$quantile\"}",
     "legendFormat": "net_version_success"
    }
   ]
  },
  {
   "title": "Duration txpool methods",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 30 },
   "targets": [
    {
     "expr": "rpc_duration_txpool_content_success{instance=~\"$instance\", job=~\"$job\", quantile=~\"$quantile\"}",
     "legendFormat": "txpool_content_success"
    }
   ]
  },
  {
   "title": "TX Pool",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 },
   "collapsed": true,
   "panels": [
    {
     "title": "Transaction Rate (tx/s)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "expr": "rate(txpool_known{job=\"$job\"}[1m])",
       "legendFormat": "Transactions"
      }
     ]
    },
    {
     "title": "Pending Transactions",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "expr": "txpool_pending{job=\"$job\"}",
       "legendFormat": "transactions"
      }
     ]
    }
   ]
  },
  {
   "title": "P2P",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 },
   "collapsed": true,
   "panels": [
    {
     "title": "Disk Activity (bytes/s)",
     "type": "stat",
     "gridPos": { "h": 6, "w": 4, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "rate(system_disk_readbytes{job=\"$job\"}[5m])",
       "legendFormat": "Read"
      },
      {
       "expr": "rate(system_disk_writebytes{job=\"$job\"}[5m])",
       "legendFormat": "Write"
      }
     ]
    },
    {
     "title": "Peers",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 20, "x": 4, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "expr": "p2p_peers{job=\"$job\"}"
      }
     ]
    },
    {
     "title": "Network Traffic (bytes/s)",
     "type": "stat",
     "gridPos": { "h": 6, "w": 4, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "rate(p2p_egress{job=\"$job\"}[5m])",
       "legendFormat": "Out"
      },
      {
       "expr": "rate(p2p_ingress{job=\"$job\"}[5m])",
       "legendFormat": "In"
      }
     ]
    },
    {
     "title": "Incoming Network (bytes/s)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "rate(p2p_ingress{job=\"$job\"}[5m])"
      }
     ]
    },
    {
     "title": "Outgoing Network (bytes/s)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "rate(p2p_egress{job=\"$job\"}[5m])"
      }
     ]
    }
   ]
  }
 ]
}