{
 "title": "OP Node",
 "tags": [
  "L2",
  "op-node",
  "sequencer",
  "application"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "job",
    "query": {
     "query": "label_values(op_node_default_info{instance=\"$instance\"},job)"
    }
   },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(op_node_default_info,instance)"
    }
   },
   {
    "name": "le",
    "query": "0.005, 0.01, 0.025, 0.05, 0.1, 0.25, 0.5, 1, 2.5, 5, 10, +Inf"
   }
  ]
 },
 "panels": [
  { "title": "Quick", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Different L1/L2 reference block numbers - finalized",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "op_node_default_refs_number{instance=~\"$instance\", job=~\"$job\",layer=\"l1\",type=\"l1_finalized\"}",
     "legendFormat": "L1 block number"
    },
    {
     "expr": "op_node_default_refs_number{instance=~\"$instance\", job=~\"$job\",layer=\"l2\",type=\"l2_finalized\"}",
     "legendFormat": "L2 block number"
    }
   ]
  },
  {
   "title": "Different L1/L2 reference block numbers - safe",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "op_node_default_refs_number{instance=~\"$instance\", job=~\"$job\",layer=\"l1\",type=\"l1_safe\"}",
     "legendFormat": "L1 block number"
    },
    {
     "expr": "op_node_default_refs_number{instance=~\"$instance\", job=~\"$job\",layer=\"l2\",type=\"l2_safe\"}",
     "legendFormat": "L2 block number"
    }
   ]
  },
  {
   "title": "Peer connected to",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 10, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "op_node_default_p2p_peer_count{instance=~\"$instance\", job=~\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total RPC requests initiated by the opnode's RPC client",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "op_node_default_rpc_client_requests_total{instance=~\"$instance\", job=~\"$job\"}",
     "legendFormat": "{{ method }}"
    }
   ]
  },
  {
   "title": "RPC client request durations",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 23, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "op_node_default_rpc_client_request_duration_seconds_bucket{instance=~\"$instance\", job=~\"$job\",le=\"$le\"}",
     "legendFormat": "{{ method }}"
    }
   ]
  }
 ]
}