{
 "title": "OP Proposer",
 "tags": [
  "L2",
  "op-proposer",
  "proposer",
  "application"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(op_proposer_default_info,instance)"
    }
   },
   {
    "name": "job",
    "query": {
     "query": "label_values(op_proposer_default_info{instance=\"$instance\"},job)"
    }
   },
   {
    "name": "le",
    "query": "0.5, 1, 2,5, 10, 20, 40, 60, 80, 100, 200, 400, 800, 1600"
   }
  ]
 },
 "panels": [
  { "title": "Quick", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Status",
   "type": "stat",
   "description": "op-proposer has finished starting up",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "op_proposer_default_up{instance=~\"$instance\", job=~\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Default Balance (ETH)",
   "type": "stat",
   "description": "balance (in ether) of account 0xC444Cf1D2E12786e5013CAE82C66b637c9dBE9c9",
   "gridPos": { "h": 4, "w": 5, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "op_proposer_default_balance{instance=~\"$instance\", job=~\"$job\"}",
     "legendFormat": "L1 block number"
    }
   ]
  },
  {
   "title": "Info",
   "type": "stat",
   "description": "Pseudo-metric tracking version and config info",
   "gridPos": { "h": 4, "w": 4, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "op_proposer_default_info{instance=~\"$instance\", job=~\"$job\"}",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Txmgr Blob Basefee Wei",
   "type": "stat",
   "description": "Latest Blob base fee (in Wei)",
   "gridPos": { "h": 4, "w": 4, "x": 13, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "op_proposer_default_txmgr_blob_basefee_wei{instance=~\"$instance\", job=~\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Txmgr Current Nonce",
   "type": "stat",
   "description": "Current nonce of the from address",
   "gridPos": { "h": 4, "w": 5, "x": 17, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "op_proposer_default_txmgr_current_nonce{instance=~\"$instance\", job=~\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Txmgr Last Publish Unix (epoch)",
   "type": "stat",
   "description": "Timestamp of last tx publish event",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "op_proposer_default_txmgr_last_publish_unix{instance=~\"$instance\", job=~\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Txmgr Pending Txs ",
   "type": "stat",
   "description": "Number of transactions pending receipts",
   "gridPos": { "h": 4, "w": 4, "x": 5, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "op_proposer_default_txmgr_pending_txs{instance=~\"$instance\", job=~\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Txmgr Basefee Wei",
   "type": "stat",
   "description": "Latest L1 base fee (in Wei)",
   "gridPos": { "h": 4, "w": 4, "x": 9, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "op_proposer_default_txmgr_basefee_wei{instance=~\"$instance\", job=~\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Txmgr RPC Error Count",
   "type": "stat",
   "description": "Temporary: Count of RPC errors (like timeouts) that have occurred",
   "gridPos": { "h": 4, "w": 4, "x": 13, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "op_proposer_default_txmgr_rpc_error_count{instance=~\"$instance\", job=~\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Txmgr Tipcap Wei",
   "type": "stat",
   "description": "Latest L1 suggested tip cap (in Wei)",
   "gridPos": { "h": 4, "w": 5, "x": 17, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "op_proposer_default_txmgr_tipcap_wei{instance=~\"$instance\", job=~\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Txmgr Tx Confirmed Latency (ms)",
   "type": "stat",
   "description": "Latency of a confirmed transaction in milliseconds",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "op_proposer_default_txmgr_tx_confirmed_latency_ms{instance=~\"$instance\", job=~\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Txmgr TX Fee (gwei )",
   "type": "stat",
   "description": "L1 gas fee for transactions in GWEI",
   "gridPos": { "h": 4, "w": 5, "x": 4, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "op_proposer_default_txmgr_tx_fee_gwei{instance=~\"$instance\", job=~\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Txmgr Publish Total",
   "type": "stat",
   "description": "Count of tx publish events",
   "gridPos": { "h": 4, "w": 4, "x": 9, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "op_proposer_default_txmgr_publish_total{instance=~\"$instance\", job=~\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Txmgr TX Gas bump",
   "type": "stat",
   "description": "Number of times a transaction gas needed to be bumped before it got included",
   "gridPos": { "h": 4, "w": 4, "x": 13, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "op_proposer_default_txmgr_tx_gas_bump{instance=~\"$instance\", job=~\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Txmgr TX Fee Total (gwei)",
   "type": "stat",
   "description": "Sum of fees spent for all transactions in GWEI",
   "gridPos": { "h": 4, "w": 5, "x": 17, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "op_proposer_default_txmgr_tx_fee_gwei_total{instance=~\"$instance\", job=~\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Basic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Tx Fee (gwei)",
   "type": "timeseries",
   "description": "Tx Fee in GWEI",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "op_proposer_default_txmgr_tx_fee_histogram_gwei_bucket{instance=~\"$instance\", job=~\"$job\", le=~\"$le\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Http metric handler requests total",
   "type": "gauge",
   "description": "Total number of scrapes by HTTP status code",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "promhttp_metric_handler_requests_total{instance=~\"$instance\", job=~\"$job\"}",
     "legendFormat": "{{code}}"
    }
   ]
  }
 ]
}